### ISSUE TITLE
Portal Arrival/Departure Buttons to trigger Beacon (one for each side of the gate)

### ISSUE THREAD

**Issue by WafflesMcDuff** [eosfrontier/ICT_Hardware#4]
A set of IoT-like devices to put around the portal:
* A light to indicate the status of the portal (incoming/not expected/etc)
* A set of buttons on the inside of the portal to set the state
* A set of buttons on the outside (customs desk?) to (re)set the state

**Comment by WafflesMcDuff** [comment]
@willemm Mar 14, 2020 at 6:58 PM
Todo: Interface the things to Beacon. For some reason, I can't get it to work on the devices themselves because the one library is not asynchronous, while the other doesn't support the type of TLS that beacon uses.

Maybe I could use the synchronous one, but that would make the lights glitchy. Or I could use another ESP and just plug that into some 5v power (USB port) somewhere just to act as a bridge.

-----
@willemm Mar 14, 2020 at 6:21 PM
Completely reworked the thing.
It now no longer uses mqtt. Instead it uses UDP packets which contain UDP-like messages. It has a sort of subscribe system so that it can send the packets directly to each device IP and not broadcast packets. It does use broadcasts to send the subscribe messages, so that the devices auto-discover each other.

Also, the devices can try different SSID-s to connect to (I programmed in my home network and gaia, although remind me to put in the correct password). In case this does not work, they fall back to one of the devices becoming an access point and the others connecting to it.

In this state, it is possible to connect to this (soft)AP and then send an udp packet containing SSID+pwd, which will trigger the devices to connect to this network. This is stored in flash so they will reconnect when rebooted.

-----
@willemm Nov 28, 2019 at 6:01 PM
Probably, however I will have to insert the correct wifi settings at the event and also set the correct IP address for the raspberry pi mqtt-broker server.

1
-----
@WafflesMcDuff Nov 27, 2019 at 11:07 AM
@willemm - How are we doing on this? If we use Gaia WiFi, are we ready to try this out on the event?

-----
@WafflesMcDuff Nov 15, 2019 at 12:25 PM
@willemm -
I have Orbis for the Bastion lobby WiFi Coverage. So if it's easier to set it up to connect to Gaianet and worry about using the RPi as base station for a later iteration, then let's do that.

-----
@willemm Nov 15, 2019 at 11:56 AM
The 3D design for the two button boxes and the light box is finished. Programming has been done in so far as that they can react to two buttons.
3D design for the box containing the rPi server has not started yet.

Also I'm having trouble with communication when the esp's connection is to the rpi as access point instead of my home network. Have not yet been able to figure out what's going wrong, it seems to be dropping messages.

-----
@WafflesMcDuff Nov 14, 2019 at 10:18 AM
Hi @willemm - Are there any progress updates for this task?

-----
@WafflesMcDuff Oct 17, 2019 at 10:22 PM
If it could be designed so the charging port is accessible, that would be awesome

-----
@willemm Oct 17, 2019 at 3:36 PM
The battery box has a micro usb port for battery charging and does support charging-while-running, however this would need to be routed to the outside (or the battery module would have to be placed right up against the edge).

I will look into designing a port into the 3d model for the cases.

There is also an option to switch out the batteries (they are 18650 li-ion cells) but I don't think I have enough spares atm.

-----

@WafflesMcDuff Oct 17, 2019 at 11:02 AM
Will the battery box have an option to plug in just in case?

-----
@willemm Oct 10, 2019 at 11:19 AM
Button devices are run by an esp8266 module (which runs wifi) and a battery box that will hopefully last the event.

They are planned to communicate via mqtt, which needs a broker running. This broker is planned to run on an rPi, which will (maybe) double as customs PC.

**Comment by willemm** [comment]
Update: I have an iot sonoff plugswitch running custom firmware that does the beacon interfacing.  So just plug that in somewhere (maybe don't plug something important into it because it could decide to turn the power on or off of whatever is plugged into it)

Code is (also) in https://github.com/eosfrontier/mqtt-items along with 3D designs.
